name: 'Setup'
description: 'Setup, Install and Test'
inputs:
  app-name:
    description: Name of the application in /lighty-applications
    required: true
runs:
  using: "composite"
  steps:
    - name: Install socat
      run: |
        sudo apt-get -y install socat
      shell: bash
    - name: Load image to minikube
      run: |
        minikube kubectl -- create serviceaccount tiller --namespace kube-system
        minikube kubectl -- create clusterrolebinding tiller-cluster-rule \
        --clusterrole=cluster-admin \
        --serviceaccount=kube-system:tiller
        helm init --stable-repo-url https://charts.helm.sh/stable --service-account tiller --wait
      shell: bash
    - name: Helm version
      run: helm version
      shell: bash
    - name: Kubernetes version
      run: minikube kubectl -- version
      shell: bash
    - name: Maven install + build docker image
      run: mvn install -Pdocker -DskipTests
      shell: bash
    - name: Start app in docker container
      run: |
        echo "Exporting Docker image to .tar ..."
        image_name=$(mvn help:evaluate -f lighty-applications/${{ inputs.app-name }}-aggregator/${{ inputs.app-name }}-docker/pom.xml -Dexpression=image.name -q -DforceStdout)
        docker save --output="./${{ inputs.app-name }}.tar" $image_name
        echo "Loading docker image to minikube"
        docker load --input ./${{ inputs.app-name }}.tar
        rm ./${{ inputs.app-name }}.tar
      shell: bash
    - name: Install app helm chart
      run: |
        helm install lighty-applications/${{ inputs.app-name }}-aggregator/${{ inputs.app-name }}-helm/helm/${{ inputs.app-name }}-helm --name ${{ inputs.app-name }}
        sleep 35 # Wait for app to start
      shell: bash
    - name: Run apps testing scripts
      run: |
        chmod +x "${GITHUB_WORKSPACE}/.github/workflows/${{ inputs.app-name }}/tests-${{ inputs.app-name }}.sh"
        # run script
        "${GITHUB_WORKSPACE}/.github/workflows/${{ inputs.app-name }}/tests-${{ inputs.app-name }}.sh"
      shell: bash
