checks:
  method-count:
    enabled: true
    config:
      threshold: 100
  method-lines:
    enabled: true
    config:
      threshold: 200
plugins:
  sonar-java:
    enabled: true
  pmd:
    enabled: true
  checkstyle:
    enabled: true

