apiVersion: v1

metadata:
  name: {{ include "lighty-rcgnmi-app-helm.fullname" . }}
kind: ConfigMap
data:
  lighty-config.json: |
    {
      "controller":{
        "restoreDirectoryPath":"./clustered-datastore-restore",
        "maxDataBrokerFutureCallbackQueueSize":1000,
        "maxDataBrokerFutureCallbackPoolSize":10,
        "metricCaptureEnabled":false,
        "mailboxCapacity":1000,
        "moduleShardsConfig": "configuration/initial/module-shards.conf",
        "modulesConfig": "configuration/initial/modules.conf",
        "domNotificationRouterConfig":{
          "queueDepth":65536,
          "spinTime":0,
          "parkTime":0,
          "unit":"MILLISECONDS"
        },
        "actorSystemConfig":{
          "akkaConfigPath":"singlenode/akka-default.conf",
          "factoryAkkaConfigPath":"singlenode/factory-akka-default.conf"
        },
        "schemaServiceConfig":{
          "topLevelModels":[
            { "nameSpace": "urn:opendaylight:params:xml:ns:yang:mdsal:core:general-entity", "name": "odl-general-entity", "revision": "2015-09-30" },
            { "nameSpace": "urn:ietf:params:xml:ns:yang:ietf-yang-library", "name": "ietf-yang-library", "revision": "2016-04-09" },
            { "nameSpace": "urn:ietf:params:xml:ns:yang:ietf-restconf-monitoring", "name": "ietf-restconf-monitoring", "revision": "2017-01-26" },
            { "nameSpace": "urn:ietf:params:xml:ns:yang:ietf-yang-types", "name": "ietf-yang-types", "revision": "2010-09-24" },
            { "nameSpace": "instance:identifier:patch:module", "name": "instance-identifier-patch-module", "revision": "2015-11-21" },
            { "nameSpace": "urn:ietf:params:xml:ns:yang:iana-if-type", "name": "iana-if-type", "revision": "2014-05-08" },
            { "nameSpace": "urn:opendaylight:params:xml:ns:yang:controller:config:actor-system-provider:impl", "name": "actor-system-provider-impl", "revision": "2015-10-05" },
            { "nameSpace": "urn:ietf:params:xml:ns:yang:ietf-network-topology", "name": "ietf-network-topology", "revision": "2015-06-08" },
            { "nameSpace": "urn:opendaylight:params:xml:ns:yang:controller:md:sal:clustering:entity-owners", "name": "entity-owners", "revision": "2015-08-04" },
            { "nameSpace": "urn:ietf:params:xml:ns:yang:ietf-access-control-list", "name": "ietf-access-control-list", "revision": "2016-02-18" },
            { "nameSpace": "config:aaa:authn:encrypt:service:config", "name": "aaa-encrypt-service-config", "revision": "2016-09-15" },
            { "nameSpace": "urn:ietf:params:xml:ns:yang:ietf-lisp-address-types", "name": "ietf-lisp-address-types", "revision": "2015-11-05" },
            { "nameSpace": "subscribe:to:notification", "name": "subscribe-to-notification", "revision": "2016-10-28" },
            { "nameSpace": "urn:opendaylight:params:xml:ns:yang:controller:config:concurrent-data-broker", "name": "odl-concurrent-data-broker-cfg", "revision": "2014-11-24" },
            { "nameSpace": "urn:opendaylight:params:xml:ns:yang:controller:md:sal:core:general-entity", "name": "general-entity", "revision": "2015-08-20" },
            { "nameSpace": "urn:opendaylight:params:xml:ns:yang:controller:md:sal:dom:pingpong", "name": "opendaylight-pingpong-broker", "revision": "2014-11-07" },
            { "nameSpace": "urn:sal:restconf:event:subscription", "name": "sal-remote-augment", "revision": "2014-07-08" },
            { "nameSpace": "urn:opendaylight:params:xml:ns:yang:controller:netty", "name": "netty", "revision": "2013-11-19" },
            { "nameSpace": "urn:ietf:params:xml:ns:yang:ietf-yang-library", "name": "ietf-yang-library", "revision": "2016-06-21" },
            { "nameSpace": "urn:ietf:params:xml:ns:yang:ietf-restconf", "name": "ietf-restconf", "revision": "2013-10-19" },
            { "nameSpace": "urn:opendaylight:params:xml:ns:yang:controller:md:sal:cluster:admin", "name": "cluster-admin", "revision": "2015-10-13" },
            { "nameSpace": "urn:opendaylight:params:xml:ns:yang:md:sal:config:impl:cluster-singleton-service", "name": "cluster-singleton-service-impl", "revision": "2016-07-18" },
            { "nameSpace": "urn:opendaylight:params:xml:ns:yang:controller:md:sal:clustering:prefix-shard-configuration", "name": "prefix-shard-configuration", "revision": "2017-01-10" },
            { "nameSpace": "urn:opendaylight:params:xml:ns:yang:controller:inmemory-datastore-provider", "name": "opendaylight-inmemory-datastore-provider", "revision": "2014-06-17" },
            { "nameSpace": "urn:opendaylight:params:xml:ns:yang:controller:md:sal:binding:impl", "name": "opendaylight-sal-binding-broker-impl", "revision": "2013-10-28" },
            { "nameSpace": "urn:ietf:params:xml:ns:yang:ietf-restconf", "name": "ietf-restconf", "revision": "2017-01-26" },
            { "nameSpace": "urn:ietf:params:xml:ns:netmod:notification", "name": "nc-notifications", "revision": "2008-07-14" },
            { "nameSpace": "urn:opendaylight:l2:types", "name": "opendaylight-l2-types", "revision": "2013-08-27" },
            { "nameSpace": "urn:opendaylight:params:xml:ns:yang:controller:config:distributed-datastore-provider", "name": "distributed-datastore-provider", "revision": "2014-06-12" },
            { "nameSpace": "urn:opendaylight:params:xml:ns:yang:controller:config:legacy-entity-ownership-service-provider", "name": "opendaylight-legacy-entity-ownership-service-provider", "revision": "2016-02-26" },
            { "nameSpace": "urn:lighty:gnmi:topology", "name": "gnmi-topology", "revision": "2021-03-16"},
            { "nameSpace": "urn:lighty:gnmi:yang:storage", "name": "gnmi-yang-storage", "revision": "2021-03-31"},
            { "nameSpace": "urn:lighty:gnmi:certificate:storage", "name": "gnmi-certificate-storage", "revision": "2021-05-04"}
          ]
        }
      },
      "restconf":{
        "inetAddress":"0.0.0.0",
        "httpPort":8888,
        "webSocketPort": 8181,
        "restconfServletContextPath":"/restconf",
        "jsonRestconfServiceType": "DRAFT_18"
      }
    }

  akka-node-k8s.conf: |
    akka {

      log-level = "debug"

      actor {
        provider = "akka.cluster.ClusterActorRefProvider"
      }

      remote {
        netty.tcp {
          hostname = ${?HOSTNAME}
          port = {{ .Values.lighty.akka.remotingPort }}
          bind-hostname = 0.0.0.0
          bind-port = {{ .Values.lighty.akka.remotingPort }}
        }
      }

      cluster {
        seed-nodes = []
        roles = [
          "{{ .Values.lighty.akka.memberNamePrefix }}"${?HOSTNAME}
        ]
        downing-provider-class = "akka.cluster.sbr.SplitBrainResolverProvider"
        split-brain-resolver {
          active-strategy = "{{ .Values.lighty.akka.sbrStrategy }}"
        }
      }

      management.http.hostname = ${?HOSTNAME}
      management.http.bind-hostname = "0.0.0.0"
      management.http.port = {{ .Values.lighty.akka.managementPort }}
      management.http.bind-port = {{ .Values.lighty.akka.managementPort }}

      management.cluster.bootstrap {
        new-cluster-enabled = on
        contact-point-discovery {
          required-contact-point-nr = {{ .Values.lighty.akka.minimumClusterNodes }} // minimun number of nodes to bootstrap the cluster
        }
      }

      discovery {
        method = kubernetes-api
        kubernetes-api {
          class = akka.discovery.kubernetes.KubernetesApiServiceDiscovery
          pod-namespace = {{ .Values.lighty.akka.discovery.podNamespace | quote }} // in which namespace cluster is running
          pod-label-selector = "{{ .Values.lighty.akka.discovery.podSelectorName }}={{ .Values.lighty.akka.discovery.podSelectorValue }}" // selector - to find other cluster nodes
          pod-port-name = {{ .Values.lighty.akka.discovery.portName | quote }} // name of cluster management port
        }
      }

      lighty-kubernetes {
        pod-restart-timeout = 30
      }

      persistence {
        # You can choose to put the snapshots/journal directories somewhere else by modifying
        # the following two properties. The directory location specified may be a relative or absolute path.

        journal.leveldb.dir = "target/journal"
        snapshot-store.local.dir = "target/snapshots"
        # Use lz4 compression for LocalSnapshotStore snapshots
        snapshot-store.local.use-lz4-compression = false
        # Size of blocks for lz4 compression: 64KB, 256KB, 1MB or 4MB
        snapshot-store.local.lz4-blocksize = 256KB

        journal {
          leveldb {
            # Set native = off to use a Java-only implementation of leveldb.
            # Note that the Java-only version is not currently considered by Akka to be production quality,
            # but being Java-only makes it work also on platforms where native leveldb is not available.

            #native = on
          }
        }
      }

    }
