apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lighty-rcgnmi-app-helm.fullname" . }}
  labels:
    {{- include "lighty-rcgnmi-app-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.lighty.replicaCount }}
  selector:
    matchLabels:
      {{- include "lighty-rcgnmi-app-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "lighty-rcgnmi-app-helm.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: {{ .Values.deploymentSecurity.runAsUser }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.name }}:{{ .Values.image.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: [ "-c","{{ .Values.lighty.configDirectoryName }}/{{ .Values.lighty.configFilename }}"]
          volumeMounts:
            - name: config-volume
              mountPath: {{ .Values.lighty.workdir }}/{{ .Values.lighty.configDirectoryName }}
          startupProbe:
            httpGet:
              path: /restconf/data/network-topology:network-topology
              port: {{ .Values.lighty.restconf.restconfPort }}
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 20
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /restconf/data/network-topology:network-topology
              port: {{ .Values.lighty.restconf.restconfPort }}
            periodSeconds: 15
            failureThreshold: 3
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /restconf/data/network-topology:network-topology
              port: {{ .Values.lighty.restconf.restconfPort }}
            periodSeconds: 15
            failureThreshold: 3
            timeoutSeconds: 1
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: {{ .Values.deploymentSecurity.runAsUser }}
            capabilities:
              drop:
                - all
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            {{- if .Values.lighty.jmx.enableJmxRemoting }}
            - name: JAVA_OPTS
              value: "-Dcom.sun.management.jmxremote
                      -Dcom.sun.management.jmxremote.authenticate=false
                      -Dcom.sun.management.jmxremote.ssl=false
                      -Dcom.sun.management.jmxremote.local.only=false
                      -Dcom.sun.management.jmxremote.port={{ .Values.lighty.jmx.jmxPort }}
                      -Dcom.sun.management.jmxremote.rmi.port={{ .Values.lighty.jmx.jmxPort }}
                      -Djava.rmi.server.hostname=127.0.0.1
                      -Dlog4j.configurationFile={{ .Values.lighty.configDirectoryName }}/{{ .Values.lighty.loggerConfigFilename }}"
            {{ else }}
            - name: JAVA_OPTS
              value: "-Dlog4j2.disable.jmx=true
                      -Dlog4j.configurationFile={{ .Values.lighty.configDirectoryName }}/{{ .Values.lighty.loggerConfigFilename }}"
            {{- end }}
          ports:
            # pekko remoting
            - name: remoting
              containerPort: {{ .Values.lighty.pekko.remotingPort }}
              protocol: TCP
            # When
            # pekko.management.cluster.bootstrap.contact-point-discovery.port-name
            # is defined, it must correspond to this name:
            - name: management
              containerPort: {{ .Values.lighty.pekko.managementPort }}
              protocol: TCP
            # restconf port
            - name: restconf
              containerPort: {{ .Values.lighty.restconf.restconfPort }}
              protocol: TCP
              {{- if .Values.lighty.jmx.enableJmxRemoting }}
              # JMX port on which JMX server is listening
            - name: jmx
              containerPort: {{ .Values.lighty.jmx.jmxPort }}
              protocol: TCP
              {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "lighty-rcgnmi-app-helm.fullname" . }}
