{{- if .Values.ingress.useIngress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "lighty-rcgnmi-app-helm.fullname" . }}
spec:
  rules:
    - host: {{ .Values.ingress.restconfHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "lighty-rcgnmi-app-helm.fullname" . }}
                port:
                  number: {{ .Values.lighty.restconf.restconfPort }}
    {{- if .Values.ingress.exposeManagement }}
    - host: {{ .Values.ingress.managementHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "lighty-rcgnmi-app-helm.fullname" . }}
                port:
                  number: {{ .Values.lighty.pekko.managementPort }}
    {{- end }}
  {{- end }}
