apiVersion: v1
kind: Service
metadata:
  name: {{ include "lighty-rcgnmi-app-helm.fullname" . }}
spec:
  {{- if .Values.nodePort.useNodePort }}
  type: NodePort
  {{- end}}
  ports:
    {{- if .Values.nodePort.exposeManagement }}
    - protocol: TCP
      name: http-pekko
      port: {{ .Values.lighty.pekko.managementPort }}
      {{- if .Values.nodePort.useNodePort }}
      targetPort: {{ .Values.lighty.pekko.managementPort }}
      nodePort: {{ .Values.nodePort.managementNodePort }}
      {{- end }}
    {{- end }}
    - protocol: TCP
      name: http-restconf
      port: {{ .Values.lighty.restconf.restconfPort }}
      {{- if .Values.nodePort.useNodePort }}
      targetPort: {{ .Values.lighty.restconf.restconfPort }}
      nodePort: {{ .Values.nodePort.restconfNodePort }}
      {{- end }}
  selector:
    {{- include "lighty-rcgnmi-app-helm.selectorLabels" . | nindent 4 }}
