apiVersion: v1
kind: Pod
metadata:
  name: netconf-simulator
  labels:
    app: netconf-simulator
spec:
  containers:
    - name: netconf-simulator
      image: lighty-netconf-simulator:latest
      ports:
        - containerPort: 17830
      imagePullPolicy: IfNotPresent