FROM openjdk:11-jre-slim

COPY target/lighty-cluster-app-12.1.2-bin.zip /

RUN apt-get update && apt-get install unzip \
    && unzip /lighty-cluster-app-12.1.2-bin.zip \
    && rm /lighty-cluster-app-12.1.2-bin.zip

ENTRYPOINT ["/lighty-cluster-app-12.1.2/start-controller-node-k8s.sh"]
