FROM openjdk:8-jdk-alpine
COPY target/lighty-cluster-app-10.2.1-SNAPSHOT-bin.zip /
RUN unzip /lighty-cluster-app-10.2.1-SNAPSHOT-bin.zip
RUN rm /lighty-cluster-app-10.2.1-SNAPSHOT-bin.zip
ENTRYPOINT ["/lighty-cluster-app-10.2.1-SNAPSHOT/start-controller-node-k8s.sh"]
