name: Test and setup lighty application

on:
  workflow_call:
    inputs:
      app-name:
        required: true
        type: string
      test-script-file:
        required: true
        type: string
      override-helm-values:
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      APP_NAME: ${{ inputs.app-name }}
      OVERRIDE_HELM_VALUES: ${{ inputs.override-helm-values }}
      TEST_SCRIPT_FILE: ${{ inputs.test-script-file }}
    steps:
      - name: Clone Repository
        uses: actions/checkout@v6
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9
      - name: Cache Maven packages
        uses: actions/cache@v5
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.15.0
        with:
          minikube version: 'v1.35.0'
          kubernetes version: 'v1.33.0'
          github token: ${{ secrets.GITHUB_TOKEN }}
      - name: Start Minikube cluster
        run: minikube start
      - name: Install helm v3.6.2
        uses: azure/setup-helm@v1.1
        with:
          version: '3.7.1'
      - name: Install socat
        run: |
          sudo apt-get -y install socat
        shell: bash
      - name: Helm version
        run: helm version
        shell: bash
      - name: Kubernetes version
        run: minikube kubectl -- version
        shell: bash
      - name: Maven install + build docker image
        run: mvn install -B -Pdocker -DskipTests
        shell: bash
      - name: Start ${{ inputs.app-name }} in docker container
        run: |
          echo "Exporting Docker image to .tar ..."
          image_name=$(mvn help:evaluate -f "lighty-applications/${APP_NAME}-aggregator/${APP_NAME}-docker/pom.xml" -Dexpression=image.name -q -DforceStdout)
          docker save --output="./${APP_NAME}.tar" "$image_name"
          echo "Loading docker image to minikube"
          docker load --input "./${APP_NAME}.tar"
          rm "./${APP_NAME}.tar"
        shell: bash
      - name: Install app helm chart
        run: |
          if [ "$OVERRIDE_HELM_VALUES" == "" ]; then
              echo "Use default helm values"
              helm install "$APP_NAME" "lighty-applications/${APP_NAME}-aggregator/${APP_NAME}-helm/helm/${APP_NAME}-helm"
          else
              echo "Set helm values to: $OVERRIDE_HELM_VALUES"
              helm install "$APP_NAME" "lighty-applications/${APP_NAME}-aggregator/${APP_NAME}-helm/helm/${APP_NAME}-helm" \
                  --set "$OVERRIDE_HELM_VALUES"
          fi
          sleep 35 # Wait for app to start
        shell: bash
      - name: Run apps testing scripts
        run: |
          chmod +x "$TEST_SCRIPT_FILE"
          # run script
          "$TEST_SCRIPT_FILE"
        shell: bash